### ISSUE TITLE
Sort locally-stored referenced files as well?

### ISSUE THREAD

**Issue by philCryoport** [thim81/asyncapi-format#13]
Hi there,

For readability and re-usability, we have extracted the `schemas` out of the primary AsyncAPI YAML file into a file `./components/schemas.yaml` -- and then have lots of `$ref` entries in the main AsyncAPI YAML file, i.e.:

```
...
schemas:
  foo_enum:
     $ref: './components/schemas.yaml#/components/schemas/foo_enum'
```

How do I use the application to sort that child / referred-to file?
